@startuml
class Club {
    -String clubName
    -String clubDescription
    -String clubPostalCode
    -BigDecimal clubMembershipFee
    -List<Rider> riders
    -List<Ride> rides

    .. Getters, Setters, Constructor ..
}
@enduml
